export const RAW_DNS_SERVERS = [
  {
    name: "ControlD Standard",
    url: "https://freedns.controld.com/p0",
    type: "post",
    allowCors: false,
    ips: [],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Canadian Shield Private",
    url: "https://private.canadianshield.cira.ca/dns-query",
    type: "post",
    allowCors: false,
    ips: ["2620:10A:80BB::10", "2620:10A:80BC::10"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "government"
  },
  {
    name: "Doh.sb",
    url: "https://doh.sb/dns-query",
    type: "post",
    allowCors: false,
    ips: ["185.222.222.222", "45.11.45.11"],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Doh.tiar",
    url: "https://doh.tiar.app/dns-query",
    type: "post",
    allowCors: false,
    ips: ["174.138.21.128", "174.138.29.175"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Doh.xfinity",
    url: "https://doh.xfinity.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["75.75.75.75", "75.75.76.76"],
    country: "🇺🇸 美国",
    noLogs: false,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Security",
    url: "https://security.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.2", "1.0.0.2", "2606:4700:4700::1112", "2606:4700:4700::1002"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Family",
    url: "https://family.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.3", "1.0.0.3", "2606:4700:4700::1113", "2606:4700:4700::1003"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Malware",
    url: "https://malware.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.2", "1.0.0.2", "2606:4700:4700::1112", "2606:4700:4700::1002"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Adult",
    url: "https://adult.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.3", "1.0.0.3", "2606:4700:4700::1113", "2606:4700:4700::1003"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Dyndns",
    url: "https://doh.dyndns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["216.146.35.35", "216.146.36.36"],
    country: "🇺🇸 美国",
    noLogs: false,
    jurisdiction: "美国",
    transparency: false,
    dnssec: false,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Gcore DNS",
    url: "https://dns.gcore.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["2.56.220.2", "95.85.95.85"],
    country: "🇱🇺 卢森堡",
    noLogs: true,
    jurisdiction: "卢森堡",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Hostux DNS",
    url: "https://dns.hostux.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["185.26.126.37", "185.26.126.38"],
    country: "🇱🇺 卢森堡",
    noLogs: true,
    jurisdiction: "卢森堡",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Ibksturm DNS",
    url: "https://ibksturm.synology.me/dns-query",
    type: "post",
    allowCors: false,
    ips: ["213.196.191.96", "2001:1620:2777:1::10"],
    country: "🇦🇹 奥地利",
    noLogs: true,
    jurisdiction: "奥地利",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Lelux DNS",
    url: "https://resolver-eu.lelux.fi/dns-query",
    type: "post",
    allowCors: false,
    ips: ["51.158.147.50", "2001:bc8:47a0:1a04::1"],
    country: "🇫🇮 芬兰",
    noLogs: true,
    jurisdiction: "芬兰",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "LibreDNS Ads",
    url: "https://doh.libredns.gr/ads",
    type: "post",
    allowCors: false,
    ips: ["116.202.176.26", "2a01:4f8:1c0c:40db::1"],
    country: "🇬🇷 希腊",
    noLogs: true,
    jurisdiction: "希腊",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "community"
  },
  {
    name: "Mrkaran DNS",
    url: "https://dns.mrkaran.dev/dns-query",
    type: "post",
    allowCors: false,
    ips: ["139.59.48.222", "2400:6180:0:d0::d9:d001"],
    country: "🇮🇳 印度",
    noLogs: true,
    jurisdiction: "印度",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Njalla DNS",
    url: "https://dns.njal.la/dns-query",
    type: "post",
    allowCors: false,
    ips: ["95.215.19.53", "2001:67c:2354:2::53"],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Oszx DNS",
    url: "https://dns.oszx.co/dns-query",
    type: "post",
    allowCors: false,
    ips: ["51.38.83.141", "2001:41d0:801:2000::d64"],
    country: "🇬🇧 英国",
    noLogs: true,
    jurisdiction: "英国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Puredns",
    url: "https://puredns.org/dns-query",
    type: "post",
    allowCors: false,
    ips: ["174.138.29.175", "174.138.21.128"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Rubyfish DNS",
    url: "https://dns.rubyfish.cn/dns-query",
    type: "post",
    allowCors: false,
    ips: ["118.89.110.78", "47.96.179.163"],
    country: "🇨🇳 中国",
    noLogs: false,
    jurisdiction: "中国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Scaleway DNS",
    url: "https://dns.scaleway.fr/dns-query",
    type: "post",
    allowCors: false,
    ips: ["51.158.147.50", "2001:bc8:47a0:1a04::1"],
    country: "🇫🇷 法国",
    noLogs: true,
    jurisdiction: "法国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Trinkwasser DNS",
    url: "https://trinkwasser.rs/dns-query",
    type: "post",
    allowCors: false,
    ips: ["78.47.64.161", "2a01:4f8:c2c:123f::1"],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "UsablePrivacy Adfree",
    url: "https://adfree.usableprivacy.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.154.153.153", "2001:67c:28a4::1"],
    country: "🇪🇺 欧盟",
    noLogs: true,
    jurisdiction: "欧盟",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "Wevpn DNS",
    url: "https://dns.wevpn.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["185.121.177.177", "169.239.202.202"],
    country: "🇭🇰 香港",
    noLogs: true,
    jurisdiction: "香港",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Aaflalo DNS",
    url: "https://dns.aaflalo.me/dns-query",
    type: "post",
    allowCors: false,
    ips: ["168.235.81.167", "2a03:4000:7:c4c::2"],
    country: "🇫🇷 法国",
    noLogs: true,
    jurisdiction: "法国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Adhole DNS",
    url: "https://doh.adhole.org/dns-query",
    type: "post",
    allowCors: false,
    ips: ["176.103.130.130", "176.103.130.131"],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "Alekberg DNS",
    url: "https://dnsse.alekberg.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["45.153.187.96", "2001:67c:2b0::4"],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "BlahDNS CH",
    url: "https://doh-ch.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["45.91.92.121", "2a0e:dc0:6:23::2"],
    country: "🇨🇭 瑞士",
    noLogs: true,
    jurisdiction: "瑞士",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "BlahDNS US",
    url: "https://doh-us.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["108.181.224.13", "2001:19f0:6c01:1b7d:5400:2ff:fe71:bc9"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "BlahDNS JP",
    url: "https://doh-jp.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: [],
    country: "🇯🇵 日本",
    noLogs: true,
    jurisdiction: "日本",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "BlahDNS DE",
    url: "https://doh-de.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: [],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "BlahDNS FI",
    url: "https://doh-fi.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: [],
    country: "🇫🇮 芬兰",
    noLogs: true,
    jurisdiction: "芬兰",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "BlahDNS SG",
    url: "https://doh-sg.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: [],
    country: "🇸🇬 新加坡",
    noLogs: true,
    jurisdiction: "新加坡",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "CIRCL DNS",
    url: "https://dns.circl.lu/dns-query",
    type: "post",
    allowCors: false,
    ips: ["185.194.93.2", "2001:a18:1::29"],
    country: "🇱🇺 卢森堡",
    noLogs: true,
    jurisdiction: "卢森堡",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "government"
  },
  {
    name: "ControlD Unfiltered",
    url: "https://freedns.controld.com/uncensored",
    type: "post",
    allowCors: false,
    ips: ["76.76.2.11", "76.223.122.150"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "ControlD Family",
    url: "https://freedns.controld.com/family",
    type: "post",
    allowCors: false,
    ips: ["76.76.2.3", "76.223.122.150"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Crypto.sx DNS",
    url: "https://doh.crypto.sx/dns-query",
    type: "post",
    allowCors: false,
    ips: ["195.201.114.64", "2a01:4f8:1c1c:5e77::1"],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Dns0 Zero",
    url: "https://zero.dns0.eu/dns-query",
    type: "post",
    allowCors: false,
    ips: [],
    country: "🇪🇺 欧盟",
    noLogs: true,
    jurisdiction: "欧盟",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "nonprofit"
  },
  {
    name: "Dnswatch",
    url: "https://resolver2.dns.watch/dns-query",
    type: "post",
    allowCors: false,
    ips: ["84.200.69.80", "84.200.70.40"],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Doh.cleanbrowsing.adult",
    url: "https://doh.cleanbrowsing.org/doh/adult-filter/",
    type: "post",
    allowCors: false,
    ips: ["185.228.168.10", "185.228.169.11"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Doh.cleanbrowsing.security",
    url: "https://doh.cleanbrowsing.org/doh/security-filter/",
    type: "post",
    allowCors: false,
    ips: ["185.228.168.9", "185.228.169.9"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Doh.cleanbrowsing.family",
    url: "https://doh.cleanbrowsing.org/doh/family-filter/",
    type: "post",
    allowCors: false,
    ips: ["185.228.168.9", "185.228.169.9"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Doh1.2.3.4",
    url: "https://doh.1.2.3.4/dns-query",
    type: "post",
    allowCors: false,
    ips: ["1.2.3.4", "1.0.0.1"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Quad9 Unsecured",
    url: "https://dns9.quad9.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["9.9.9.10", "149.112.112.10", "2620:fe::10", "2620:fe::fe:10"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "nonprofit"
  },
  {
    name: "Quad9 Secured",
    url: "https://dns11.quad9.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["9.9.9.11", "149.112.112.11", "2620:fe::11", "2620:fe::fe:11"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "nonprofit"
  },
  {
    name: "Quad9",
    url: "https://dns.quad9.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["9.9.9.9", "149.112.112.112", "2620:fe::fe", "2620:fe::9"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "nonprofit"
  },
  {
    name: "AdGuard Non-filtering",
    url: "https://unfiltered.adguard-dns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["94.140.14.140", "94.140.14.141", "2a10:50c0::1:ff", "2a10:50c0::2:ff"],
    country: "🇨🇾 塞浦路斯",
    noLogs: true,
    jurisdiction: "塞浦路斯",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare",
    url: "https://cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.1", "1.0.0.1", "2606:4700:4700::1111", "2606:4700:4700::1001"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Security",
    url: "https://security.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.2", "1.0.0.2", "2606:4700:4700::1112", "2606:4700:4700::1002"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Family",
    url: "https://family.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.3", "1.0.0.3", "2606:4700:4700::1113", "2606:4700:4700::1003"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Canadian Shield Protected",
    url: "https://protected.canadianshield.cira.ca/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.112.121.20", "149.112.122.20", "2620:10A:80BB::20", "2620:10A:80BC::20"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "government"
  },
  {
    name: "Canadian Shield Family",
    url: "https://family.canadianshield.cira.ca/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.112.121.30", "149.112.122.30", "2620:10A:80BB::30", "2620:10A:80BC::30"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "government"
  },
  {
    name: "Canadian Shield Private",
    url: "https://private.canadianshield.cira.ca/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.112.121.40", "149.112.122.40", "2620:10A:80BB::40", "2620:10A:80BC::40"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "government"
  },
  {
    name: "DNS0.eu Zero",
    url: "https://zero.dns0.eu/dns-query",
    type: "post",
    allowCors: false,
    ips: ["193.110.81.0", "185.253.5.0", "2a0f:fc80::", "2a0f:fc81::"],
    country: "🇪🇺 欧盟",
    noLogs: true,
    jurisdiction: "欧盟",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "nonprofit"
  },
  {
    name: "AdGuard Default",
    url: "https://dns.adguard.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["94.140.14.14", "94.140.14.15", "2a10:50c0::1:ff", "2a10:50c0::2:ff"],
    country: "🇨🇾 塞浦路斯",
    noLogs: true,
    jurisdiction: "塞浦路斯",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "AdGuard Family",
    url: "https://dns-family.adguard.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["94.140.14.12", "94.140.14.13", "2a10:50c0::1:ff", "2a10:50c0::2:ff"],
    country: "🇨🇾 塞浦路斯",
    noLogs: true,
    jurisdiction: "塞浦路斯",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
];

// 精简版「可信 DNS」列表：用于 trusted 模式和默认占位，完整列表仅在 all-in 模式下从 /servers.json 按需加载。
export const DNS_SERVERS = RAW_DNS_SERVERS.filter((server) => {
  if (server.trustLevel === "personal" || server.trustLevel === "community") {
    return false;
  }
  if (
    server.name === "Doh.xfinity" ||
    server.name === "Dyndns" ||
    server.name === "Gcore DNS" ||
    server.name === "Scaleway DNS" ||
    server.name === "Wevpn DNS" ||
    server.name === "Njalla DNS"
  ) {
    return false;
  }
  return true;
});

export const PRIVACY_DNS_SERVERS = [
  {
    name: "Quad9 Unsecured",
    url: "https://dns9.quad9.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["9.9.9.10", "149.112.112.10", "2620:fe::10", "2620:fe::fe:10"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "nonprofit"
  },
  {
    name: "Quad9 Secured",
    url: "https://dns11.quad9.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["9.9.9.11", "149.112.112.11", "2620:fe::11", "2620:fe::fe:11"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "nonprofit"
  },
  {
    name: "AdGuard Non-filtering",
    url: "https://unfiltered.adguard-dns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["94.140.14.140", "94.140.14.141", "2a10:50c0::1:ff", "2a10:50c0::2:ff"],
    country: "🇨🇾 塞浦路斯",
    noLogs: true,
    jurisdiction: "塞浦路斯",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare",
    url: "https://cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.1", "1.0.0.1", "2606:4700:4700::1111", "2606:4700:4700::1001"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Security",
    url: "https://security.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.2", "1.0.0.2", "2606:4700:4700::1112", "2606:4700:4700::1002"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Cloudflare Family",
    url: "https://family.cloudflare-dns.com/dns-query",
    type: "get",
    allowCors: true,
    ips: ["1.1.1.3", "1.0.0.3", "2606:4700:4700::1113", "2606:4700:4700::1003"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Canadian Shield Protected",
    url: "https://protected.canadianshield.cira.ca/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.112.121.20", "149.112.122.20", "2620:10A:80BB::20", "2620:10A:80BC::20"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "government"
  },
  {
    name: "Canadian Shield Family",
    url: "https://family.canadianshield.cira.ca/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.112.121.30", "149.112.122.30", "2620:10A:80BB::30", "2620:10A:80BC::30"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "government"
  },
  {
    name: "Canadian Shield Private",
    url: "https://private.canadianshield.cira.ca/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.112.121.40", "149.112.122.40", "2620:10A:80BB::40", "2620:10A:80BC::40"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "government"
  },
  {
    name: "DNS0.eu Kids",
    url: "https://kids.dns0.eu/dns-query",
    type: "post",
    allowCors: false,
    ips: ["193.110.81.1", "185.253.5.1"],
    country: "🇪🇺 欧盟",
    noLogs: true,
    jurisdiction: "欧盟",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "nonprofit"
  },
  {
    name: "ControlD Unfiltered",
    url: "https://freedns.controld.com/uncensored",
    type: "post",
    allowCors: false,
    ips: ["76.76.2.11", "76.223.122.150"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "ControlD Family",
    url: "https://freedns.controld.com/family",
    type: "post",
    allowCors: false,
    ips: ["76.76.2.3", "76.223.122.150"],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "ControlD Standard",
    url: "https://freedns.controld.com/p0",
    type: "post",
    allowCors: false,
    ips: [],
    country: "🇨🇦 加拿大",
    noLogs: true,
    jurisdiction: "加拿大",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "LibreDNS Ads",
    url: "https://doh.libredns.gr/ads",
    type: "post",
    allowCors: false,
    ips: ["116.202.176.26", "2a01:4f8:1c0c:40db::1"],
    country: "🇬🇷 希腊",
    noLogs: true,
    jurisdiction: "希腊",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "community"
  },
  {
    name: "BlahDNS CH",
    url: "https://doh-ch.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["45.91.92.121", "2a0e:dc0:6:23::2"],
    country: "🇨🇭 瑞士",
    noLogs: true,
    jurisdiction: "瑞士",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "BlahDNS US",
    url: "https://doh-us.blahdns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["108.181.224.13", "2001:19f0:6c01:1b7d:5400:2ff:fe71:bc9"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "DNSWarden Ad-blocker",
    url: "https://doh.dnswarden.com/adblock",
    type: "post",
    allowCors: false,
    ips: ["116.203.115.192", "116.203.179.248"],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "DNSWarden Uncensored",
    url: "https://doh.dnswarden.com/uncensored",
    type: "post",
    allowCors: false,
    ips: ["116.203.115.192", "116.203.179.248"],
    country: "🇩🇪 德国",
    noLogs: true,
    jurisdiction: "德国",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Njalla DNS",
    url: "https://dns.njal.la/dns-query",
    type: "post",
    allowCors: false,
    ips: ["95.215.19.53", "2001:67c:2354:2::53"],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Hostux DNS",
    url: "https://dns.hostux.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["185.26.126.37", "185.26.126.38"],
    country: "🇱🇺 卢森堡",
    noLogs: true,
    jurisdiction: "卢森堡",
    transparency: false,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "personal"
  },
  {
    name: "Nixnet DNS",
    url: "https://uncensored.any.dns.nixnet.xyz/dns-query",
    type: "post",
    allowCors: false,
    ips: ["198.98.54.105", "2001:5335:357a::105"],
    country: "🇺🇸 美国",
    noLogs: true,
    jurisdiction: "美国",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "community"
  },
  {
    name: "UsablePrivacy Adfree",
    url: "https://adfree.usableprivacy.net/dns-query",
    type: "post",
    allowCors: false,
    ips: ["149.154.153.153", "2001:67c:28a4::1"],
    country: "🇪🇺 欧盟",
    noLogs: true,
    jurisdiction: "欧盟",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "Pi-DNS.com",
    url: "https://doh.pi-dns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: ["45.67.219.208", "2a04:bdc7:100:70::abcd"],
    country: "🇩🇰 丹麦",
    noLogs: true,
    jurisdiction: "丹麦",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "personal"
  },
  {
    name: "Mullvad DNS",
    url: "https://dns.mullvad.net/dns-query",
    type: "get",
    allowCors: true,
    ips: ["194.242.2.2", "2a07:e340::2"],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Mullvad Base",
    url: "https://base.dns.mullvad.net/dns-query",
    type: "get",
    allowCors: true,
    ips: [],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: true,
    dnssec: true,
    malwareFilter: false,
    trustLevel: "enterprise"
  },
  {
    name: "Mullvad AdBlock",
    url: "https://adblock.dns.mullvad.net/dns-query",
    type: "get",
    allowCors: true,
    ips: [],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Mullvad Family",
    url: "https://family.dns.mullvad.net/dns-query",
    type: "get",
    allowCors: true,
    ips: [],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "Mullvad All",
    url: "https://all.dns.mullvad.net/dns-query",
    type: "get",
    allowCors: true,
    ips: [],
    country: "🇸🇪 瑞典",
    noLogs: true,
    jurisdiction: "瑞典",
    transparency: true,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "AdGuard",
    url: "https://dns.adguard-dns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: [
      "94.140.14.14",
      "94.140.15.15",
      "2a10:50c0::ad1:ff",
      "2a10:50c0::ad2:ff"
    ],
    country: "🇨🇾 塞浦路斯",
    noLogs: true,
    jurisdiction: "塞浦路斯",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  },
  {
    name: "AdGuard Family",
    url: "https://family.adguard-dns.com/dns-query",
    type: "post",
    allowCors: false,
    ips: [
      "94.140.14.15",
      "94.140.15.16",
      "2a10:50c0::bad1:ff",
      "2a10:50c0::bad2:ff"
    ],
    country: "🇨🇾 塞浦路斯",
    noLogs: true,
    jurisdiction: "塞浦路斯",
    transparency: false,
    dnssec: true,
    malwareFilter: true,
    trustLevel: "enterprise"
  }
];

export const ALL_DNS_SERVERS = DNS_SERVERS;

export const TEST_DOMAINS = [
  'google.com',
  'youtube.com',
  'instagram.com',
  'chatgpt.com',
  'whatsapp.com',
  'reddit.com',
  'wikipedia.org',
  'tiktok.com',
  'pinterest.com',
  'code.visualstudio.com',
  'jetbrains.com',
  'duckduckgo.com',
  'spotify.com',
  'bing.com',
  'microsoftonline.com',
  'steamcommunity.com',
  'grok.com',
  'store.steampowered.com',
  'epicgames.com',
  'claw.cloud',
  'github.com',
  'gitlab.com',
  'stackoverflow.com',
  'proton.me',
  'codeforces.com',
  'microsoft.com',
  'live.com',
  'atcoder.jp',
  'apple.com',
  'cloudflare.com',
  'oracle.com',
  'akamaihd.net',
  'gstatic.com',
  'icloud.com',
  'quora.com',
  'telegram.org',
  'ign.com',
  'rockstargames.com',
  'scholar.google.com',
  'paypal.com',
  'wordpress.com',
  'blogspot.com',
  'dropbox.com',
  'bilibili.com',
  'douyin.com',
  'xiaohongshu.com',
  'qq.com',
  'weixin.qq.com',
  'taobao.com',
  'tmall.com',
  'pinduoduo.com',
  'alipay.com',
  'cloud.tencent.com',
  'aliyun.com',
  'huawei.com',
  'gitee.com',
  'windy.com',
  'openstreetmap.org',
  'protomaps.com',
  'xiaoheihe.cn',
  'amap.com',
  'jd.com',
  '2.taobao.com',
  'meituan.com',
  'alibaba.com',
  'claude.ai',
  'deepseek.com',
  'kimi.moonshot.cn',
  'doubao.com',
  'ciciai.com',
  'openai.com',
  'pwesports.cn',
  '5eplay.com',
  'douyu.com',
  'mail.zoho.com',
  'notion.so',
  'ankiweb.net',
  'coolapk.com',
  'testflight.apple.com',
  'threads.net',
  '12306.cn',
  'airchina.com.cn'
];
